### ISSUE TITLE
Allow more than five lines of a quote

### ISSUE THREAD

**Issue by dotzenith** [dotzenith/lovesay#14]
As of now, the number of lines a quote can take up is bound above by 5. This was originally put in place simply because I didn't want the quote to take up more lines than the heart itself. After some thought, I think it makes sense to allow more than just 5 lines. 

Figure out a way to print out more than just five lines, and keep the heart the same size. Shouldn't be too hard, just a little bit of refactoring.

**Comment by dorian-adams** [comment]
Hi, I just submitted a PR for this issue and it's my first PR! This is a fun project you have going on, so I hope I submitted everything correctly. If not, I'm definitely open to suggestions and look forward to your feedback. If there's anything I could improve, please let me know and I'll update. Thanks!

**Comment by yusufraji** [comment]
I was working on this earlier, but not finished. I noticed that the `~` [here](https://github.com/dotzenith/lovesay/blob/d9587db2850ad5ed00c23d687a3a2637e22bdca0/lovesay/love.py#L25) needs to be `.` and [this line](https://github.com/dotzenith/lovesay/blob/d9587db2850ad5ed00c23d687a3a2637e22bdca0/lovesay/love.py#L120) changed to `if not quote:` for the code to work without passing any argument when running the script. So, it loads the config from the project directory.

**Comment by yusufraji** [comment]
Hello @dotzenith, I agree with your first point. Having an example quotes file in the repo was of great help when I looked into the codebase for the first time.

**Comment by dotzenith** [comment]
Hey @yusufraji I totally wasn't aware that empty sequences also evaluate to False! 

For the case of defaults, `quote` already defaults to `None` when using the cli - 
`quote: Optional[str] = typer.Argument(None, help="An arbitrary message to print", show_default=False)`

The main function is called with "" in the main script out of sheer laziness and nothing else :) but that can be confusing for someone looking at the codebase so perhaps it'd worthwhile changing that?  

Thank you so much for your feedback! It's much appreciated
